[workspace]
pr_name = "release: v{{ version }}"
pr_labels = ["release"]
release = true                      # create git tag and GitHub release
publish = false                     # don't publish to crates.io
