[book]
authors = ["elbaro"]
language = "en"
src = "src"
title = "pyro-postgres Documentation"


[rust]
edition = "2024"

[output.html]
git-repository-url = "https://github.com/elbaro/pyro-postgres"
git-repository-icon = "fab-github"
site-url = "/pyro-postgres/"
